// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuotesMicroservice.Models;

namespace QuotesMicroservice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("QuotesMicroservice.Models.QuotesMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MaxBusinessValue")
                        .HasColumnType("int");

                    b.Property<int>("MaxPropertyValue")
                        .HasColumnType("int");

                    b.Property<int>("MinBusinessValue")
                        .HasColumnType("int");

                    b.Property<int>("MinPropertyValue")
                        .HasColumnType("int");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Quotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaxBusinessValue = 3,
                            MaxPropertyValue = 3,
                            MinBusinessValue = 0,
                            MinPropertyValue = 0,
                            PropertyType = "Factory Equipment",
                            Quotes = "80000"
                        },
                        new
                        {
                            Id = 2,
                            MaxBusinessValue = 7,
                            MaxPropertyValue = 7,
                            MinBusinessValue = 4,
                            MinPropertyValue = 4,
                            PropertyType = "Factory Equipment",
                            Quotes = "50000"
                        },
                        new
                        {
                            Id = 3,
                            MaxBusinessValue = 10,
                            MaxPropertyValue = 10,
                            MinBusinessValue = 8,
                            MinPropertyValue = 8,
                            PropertyType = "Factory Equipment",
                            Quotes = "30000"
                        },
                        new
                        {
                            Id = 4,
                            MaxBusinessValue = 3,
                            MaxPropertyValue = 3,
                            MinBusinessValue = 0,
                            MinPropertyValue = 0,
                            PropertyType = "Building",
                            Quotes = "80000"
                        },
                        new
                        {
                            Id = 5,
                            MaxBusinessValue = 7,
                            MaxPropertyValue = 7,
                            MinBusinessValue = 4,
                            MinPropertyValue = 4,
                            PropertyType = "Building",
                            Quotes = "50000"
                        },
                        new
                        {
                            Id = 6,
                            MaxBusinessValue = 10,
                            MaxPropertyValue = 10,
                            MinBusinessValue = 8,
                            MinPropertyValue = 8,
                            PropertyType = "Building",
                            Quotes = "30000"
                        },
                        new
                        {
                            Id = 7,
                            MaxBusinessValue = 3,
                            MaxPropertyValue = 3,
                            MinBusinessValue = 0,
                            MinPropertyValue = 0,
                            PropertyType = "Property In Transit",
                            Quotes = "80000"
                        },
                        new
                        {
                            Id = 8,
                            MaxBusinessValue = 7,
                            MaxPropertyValue = 7,
                            MinBusinessValue = 4,
                            MinPropertyValue = 4,
                            PropertyType = "Property In Transit",
                            Quotes = "50000"
                        },
                        new
                        {
                            Id = 9,
                            MaxBusinessValue = 10,
                            MaxPropertyValue = 10,
                            MinBusinessValue = 8,
                            MinPropertyValue = 8,
                            PropertyType = "Property In Transit",
                            Quotes = "30000"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
