// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyMicroservice.Models;

namespace PolicyMicroservice.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220805080957_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PolicyMicroservice.Models.ConsumerPolicy", b =>
                {
                    b.Property<int>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AcceptanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AcceptedQuotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("ConsumerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EffectiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyStatus")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolicyId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("PolicyMicroservice.Models.PolicyMaster", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AssuredSum")
                        .HasColumnType("int");

                    b.Property<string>("BaseLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BusinessValue")
                        .HasColumnType("int");

                    b.Property<string>("ConsumerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PropertyValue")
                        .HasColumnType("int");

                    b.Property<int>("Tenure")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BuiltInPolicies");

                    b.HasData(
                        new
                        {
                            Id = "P01",
                            AssuredSum = 20000000,
                            BaseLocation = "Pune",
                            BusinessValue = 5,
                            ConsumerType = "Owner",
                            PropertyType = "Building",
                            PropertyValue = 4,
                            Tenure = 3,
                            Type = "Replacement"
                        },
                        new
                        {
                            Id = "P02",
                            AssuredSum = 40000000,
                            BaseLocation = "Chennai",
                            BusinessValue = 9,
                            ConsumerType = "Owner",
                            PropertyType = "Factory Equipment",
                            PropertyValue = 8,
                            Tenure = 1,
                            Type = "Replacement"
                        },
                        new
                        {
                            Id = "P03",
                            AssuredSum = 20000000,
                            BaseLocation = "Mumbai",
                            BusinessValue = 7,
                            ConsumerType = "Owner",
                            PropertyType = "Property in Transit",
                            PropertyValue = 6,
                            Tenure = 5,
                            Type = "Pay Back"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
